spring.application.name=api-gateway
server.port=8082
#Eureka Client
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
# spring.main.web-application-type=reactive

# spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=false

# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
# spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# Load Balancer
# spring.cloud.loadbalancer.ribbon.enabled=true

spring.cloud.gateway.routes[0].id=mstramites
spring.cloud.gateway.routes[0].uri=lb://TRAMITES-API
spring.cloud.gateway.routes[0].predicates[0]=Path=/mstramites/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/mstramites(?<remaining>.*), /api${remaining}
# spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=msnotificaciones
spring.cloud.gateway.routes[1].uri=lb://NOTIFICACIONES-API
spring.cloud.gateway.routes[1].predicates[0]=Path=/msnotificaciones/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/msnotificaciones(?<remaining>.*), /api${remaining}

spring.cloud.gateway.routes[2].id=mspersona
spring.cloud.gateway.routes[2].uri=lb://PERSONA-API
spring.cloud.gateway.routes[2].predicates[0]=Path=/mspersona/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/mspersona(?<remaining>.*), /api${remaining}

spring.cloud.gateway.routes[3].id=msarchivo
spring.cloud.gateway.routes[3].uri=lb://ARCHIVO-API
spring.cloud.gateway.routes[3].predicates[0]=Path=/msarchivo/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/msarchivo(?<remaining>.*), /api${remaining}

spring.cloud.gateway.routes[4].id=msseguridad
spring.cloud.gateway.routes[4].uri=lb://SEGURIDAD-API
spring.cloud.gateway.routes[4].predicates[0]=Path=/msseguridad/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/msseguridad(?<remaining>.*), /api${remaining}

