spring.application.name=api-gateway
server.port=${SERVER_PORT:8082}

# Rutas hacia los microservicios
spring.cloud.gateway.routes[0].id=mstramites
spring.cloud.gateway.routes[0].uri=${URI_SERVICE_TRAMITES:http://localhost:8085}
spring.cloud.gateway.routes[0].predicates[0]=Path=/mstramites/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/mstramites(?<remaining>.*), /api${remaining}

spring.cloud.gateway.routes[1].id=msnotificaciones
spring.cloud.gateway.routes[1].uri=${URI_SERVICE_NOTIFICACIONES:http://localhost:8086}
spring.cloud.gateway.routes[1].predicates[0]=Path=/msnotificaciones/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/msnotificaciones(?<remaining>.*), /api${remaining}

spring.cloud.gateway.routes[2].id=mspersona
spring.cloud.gateway.routes[2].uri=${URI_SERVICE_PERSONA:http://localhost:8084}
spring.cloud.gateway.routes[2].predicates[0]=Path=/mspersona/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/mspersona(?<remaining>.*), /api${remaining}

spring.cloud.gateway.routes[3].id=msarchivo
spring.cloud.gateway.routes[3].uri=${URI_SERVICE_ARCHIVO:http://localhost:8087}
spring.cloud.gateway.routes[3].predicates[0]=Path=/msarchivo/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/msarchivo(?<remaining>.*), /api${remaining}

spring.cloud.gateway.routes[4].id=msseguridad
spring.cloud.gateway.routes[4].uri=${URI_SERVICE_SEGURIDAD:http://localhost:8083}
spring.cloud.gateway.routes[4].predicates[0]=Path=/msseguridad/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/msseguridad(?<remaining>.*), /api${remaining}
